In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import math

In [3]:
import numpy as np, sys, site, os, glob
print("NumPy version:", np.__version__)
print("NumPy file:   ", getattr(np, "__file__", None))
print("User site:    ", site.getusersitepackages())
print("PYTHONPATH:   ", os.environ.get("PYTHONPATH"))
print("Shadow here?  ", glob.glob("./numpy*"))

NumPy version: 1.26.4
NumPy file:    /global/cfs/cdirs/m3246/ylo/conda/cmsflow_fj/lib/python3.11/site-packages/numpy/__init__.py
User site:     /global/homes/y/ylo/.local/lib/python3.11/site-packages
PYTHONPATH:    /opt/nersc/pymon
Shadow here?   []


In [4]:
from parnassus_core.experiments.cms_2011.performance.performance import (
    CMS2011Performance,
    CMS2011PlotHelper,
    CMS2011Sample,
    CMS2011PerformanceConfig,
)

In [5]:
config_dict = {
    "samples": {
        "ttbar": [
            {
                "name": "parnassus",
                "path": "QCD_noPU_rm_0truth_postprocess_9k_test_eta30Eval.root",
                "pflow_type": "fm",
                "label": "Parnassus (FM)",
            },
        ],
    }
}

In [6]:
config = CMS2011PerformanceConfig.from_dict(config_dict)

In [7]:
perf = CMS2011Performance(config)

In [8]:
config.sample_dict.keys()

dict_keys([<CMS2011Sample.TTBAR: 'ttbar'>])

In [9]:
perf.load()

Loading data for parnassus from QCD_noPU_rm_0truth_postprocess_9k_test_eta30Eval.root


In [10]:
perf.sample_data_dict[CMS2011Sample.TTBAR].filter_events()

Filtering events for PF with source Source.PF
Data(name=PF, source=Source.PF), events filtered: 9987
Filtering events for TR with source Source.TR
Data(name=TR, source=Source.TR), events filtered: 9987
Filtering events for parnassus with source Source.FM
Data(name=parnassus, source=Source.FM), events filtered: 9987


In [11]:
perf.sample_data_dict[CMS2011Sample.TTBAR].data_dict["PF"]["particle/jet/pt"]

array([array([22.8125   ,  7.65625  ,  2.46875  ,  4.1171875]),
       array([1.22070312, 2.52734375, 1.11621094, 7.921875  , 2.0390625 ,
              2.3359375 , 2.60742188, 1.92675781, 2.15429688, 5.75      ,
              4.8828125 , 1.45117188, 2.8125    , 1.94921875, 1.01757812,
              1.        , 1.82226562, 3.52734375, 1.06933594, 1.09277344,
              1.90625   , 5.26953125, 2.61523438, 1.09277344, 1.87304688]),
       array([1.20605469, 4.0703125 , 1.94921875, 1.23144531, 4.1953125 ,
              4.62109375, 2.39648438, 5.328125  , 1.23535156, 2.75      ,
              7.87109375, 1.84570312, 6.71484375, 7.51171875, 1.18261719,
              1.48339844, 1.25976562, 3.32421875, 3.74023438, 5.84375   ,
              2.20898438, 3.70898438, 3.87109375])                       ,
       ...,
       array([1.13769531, 2.734375  , 3.00195312, 2.40820312, 1.63085938,
              1.97949219, 5.65234375, 1.4140625 , 1.81933594, 1.25488281,
              4.2734375 , 2.54296

In [12]:
perf.sample_data_dict[CMS2011Sample.TTBAR].data_dict["PF"].particle_data_jet["pt"][1310]

array([ 2.92578125,  1.71484375,  3.17382812,  1.78027344,  6.1796875 ,
        1.65917969,  1.05371094,  1.234375  ,  2.87695312,  9.84375   ,
        1.52441406,  2.02539062,  1.11816406,  1.84960938,  2.72265625,
        2.75390625,  4.609375  ,  1.08789062, 24.75      ,  1.0703125 ,
        1.01660156,  4.27734375,  1.97167969,  2.22851562,  7.8515625 ,
        2.41601562,  2.58203125,  9.21875   ])

In [13]:
perf.sample_data_dict[CMS2011Sample.TTBAR].process_data()

Calculating event data for PF with source Source.PF
Calculating event data for TR with source Source.TR
Calculating event data for parnassus with source Source.FM
Processing data for PF with source Source.PF
Calculating event residuals for PF with source Source.PF against TR with source Source.TR
Matching jets for PF with source Source.PF against TR with source Source.TR


Matching jets: 100%|██████████| 9987/9987 [00:00<00:00, 10274.07it/s]


Calculating jet residuals for PF with source Source.PF against TR with source Source.TR


residuals: 100%|██████████| 9987/9987 [00:00<00:00, 48691.78it/s]


Calculating particle residuals for PF with source Source.PF against TR with source Source.TR
Split:  all


KeyError: 'tr_idx'